import { Router } from "express";
import { asyncHandler } from "../../utils/async-handler";
import { validate } from "../../middleware/validate";
import { login, register } from "./auth.controller";
import { loginSchema, registerSchema } from "./auth.schema";
import { authRateLimit } from "../../middleware/rate-limit";
const router = Router();
router.post("/register", authRateLimit, validate(registerSchema), asyncHandler(register));
router.post("/login", authRateLimit, validate(loginSchema), asyncHandler(login));
export default router;
